//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageStoreConsole.ImageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        void AddFolder(string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        System.Threading.Tasks.Task AddFolderAsync(string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFolder", ReplyAction="http://tempuri.org/IService/GetFolderResponse")]
        Sprut.Domain.Folder GetFolder(string name, System.Nullable<System.Guid> parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFolder", ReplyAction="http://tempuri.org/IService/GetFolderResponse")]
        System.Threading.Tasks.Task<Sprut.Domain.Folder> GetFolderAsync(string name, System.Nullable<System.Guid> parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagesInFolder", ReplyAction="http://tempuri.org/IService/GetImagesInFolderResponse")]
        System.Collections.Generic.List<Sprut.Domain.Image> GetImagesInFolder(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagesInFolder", ReplyAction="http://tempuri.org/IService/GetImagesInFolderResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Sprut.Domain.Image>> GetImagesInFolderAsync(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSubFolders", ReplyAction="http://tempuri.org/IService/GetSubFoldersResponse")]
        System.Collections.Generic.List<Sprut.Domain.Folder> GetSubFolders(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSubFolders", ReplyAction="http://tempuri.org/IService/GetSubFoldersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Sprut.Domain.Folder>> GetSubFoldersAsync(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadImage", ReplyAction="http://tempuri.org/IService/UploadImageResponse")]
        System.Guid UploadImage(byte[] data, string fileNameOrigin, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadImage", ReplyAction="http://tempuri.org/IService/UploadImageResponse")]
        System.Threading.Tasks.Task<System.Guid> UploadImageAsync(byte[] data, string fileNameOrigin, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImageUrl", ReplyAction="http://tempuri.org/IService/GetImageUrlResponse")]
        string GetImageUrl(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImageUrl", ReplyAction="http://tempuri.org/IService/GetImageUrlResponse")]
        System.Threading.Tasks.Task<string> GetImageUrlAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTmbUrl", ReplyAction="http://tempuri.org/IService/GetTmbUrlResponse")]
        string GetTmbUrl(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTmbUrl", ReplyAction="http://tempuri.org/IService/GetTmbUrlResponse")]
        System.Threading.Tasks.Task<string> GetTmbUrlAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ImageStoreConsole.ImageService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ImageStoreConsole.ImageService.IService>, ImageStoreConsole.ImageService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddFolder(string name, string path) {
            base.Channel.AddFolder(name, path);
        }
        
        public System.Threading.Tasks.Task AddFolderAsync(string name, string path) {
            return base.Channel.AddFolderAsync(name, path);
        }
        
        public Sprut.Domain.Folder GetFolder(string name, System.Nullable<System.Guid> parentId) {
            return base.Channel.GetFolder(name, parentId);
        }
        
        public System.Threading.Tasks.Task<Sprut.Domain.Folder> GetFolderAsync(string name, System.Nullable<System.Guid> parentId) {
            return base.Channel.GetFolderAsync(name, parentId);
        }
        
        public System.Collections.Generic.List<Sprut.Domain.Image> GetImagesInFolder(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetImagesInFolder(folderId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Sprut.Domain.Image>> GetImagesInFolderAsync(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetImagesInFolderAsync(folderId);
        }
        
        public System.Collections.Generic.List<Sprut.Domain.Folder> GetSubFolders(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetSubFolders(folderId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Sprut.Domain.Folder>> GetSubFoldersAsync(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetSubFoldersAsync(folderId);
        }
        
        public System.Guid UploadImage(byte[] data, string fileNameOrigin, string folder) {
            return base.Channel.UploadImage(data, fileNameOrigin, folder);
        }
        
        public System.Threading.Tasks.Task<System.Guid> UploadImageAsync(byte[] data, string fileNameOrigin, string folder) {
            return base.Channel.UploadImageAsync(data, fileNameOrigin, folder);
        }
        
        public string GetImageUrl(System.Guid id) {
            return base.Channel.GetImageUrl(id);
        }
        
        public System.Threading.Tasks.Task<string> GetImageUrlAsync(System.Guid id) {
            return base.Channel.GetImageUrlAsync(id);
        }
        
        public string GetTmbUrl(System.Guid id) {
            return base.Channel.GetTmbUrl(id);
        }
        
        public System.Threading.Tasks.Task<string> GetTmbUrlAsync(System.Guid id) {
            return base.Channel.GetTmbUrlAsync(id);
        }
    }
}
