//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAShop.ImagesClient.Images {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folder", Namespace="http://schemas.datacontract.org/2004/07/YAShop.ImagesHost")]
    [System.SerializableAttribute()]
    public partial class Folder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YAShop.ImagesClient.Images.Folder[] ChildrensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public YAShop.ImagesClient.Images.Folder[] Childrens {
            get {
                return this.ChildrensField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrensField, value) != true)) {
                    this.ChildrensField = value;
                    this.RaisePropertyChanged("Childrens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Image", Namespace="http://schemas.datacontract.org/2004/07/YAShop.ImagesHost")]
    [System.SerializableAttribute()]
    public partial class Image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Images.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFoldersTree", ReplyAction="http://tempuri.org/IService/GetFoldersTreeResponse")]
        YAShop.ImagesClient.Images.Folder[] GetFoldersTree(System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFoldersTree", ReplyAction="http://tempuri.org/IService/GetFoldersTreeResponse")]
        System.Threading.Tasks.Task<YAShop.ImagesClient.Images.Folder[]> GetFoldersTreeAsync(System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImages", ReplyAction="http://tempuri.org/IService/GetImagesResponse")]
        YAShop.ImagesClient.Images.Image[] GetImages(System.Nullable<System.Guid> folderId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImages", ReplyAction="http://tempuri.org/IService/GetImagesResponse")]
        System.Threading.Tasks.Task<YAShop.ImagesClient.Images.Image[]> GetImagesAsync(System.Nullable<System.Guid> folderId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        System.Guid AddFolder(string name, System.Nullable<System.Guid> parentId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        System.Threading.Tasks.Task<System.Guid> AddFolderAsync(string name, System.Nullable<System.Guid> parentId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadImage", ReplyAction="http://tempuri.org/IService/UploadImageResponse")]
        System.Guid UploadImage(string name, byte[] data, System.Nullable<System.Guid> folderId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadImage", ReplyAction="http://tempuri.org/IService/UploadImageResponse")]
        System.Threading.Tasks.Task<System.Guid> UploadImageAsync(string name, byte[] data, System.Nullable<System.Guid> folderId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RenameFolder", ReplyAction="http://tempuri.org/IService/RenameFolderResponse")]
        bool RenameFolder(System.Guid folderId, string newName, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RenameFolder", ReplyAction="http://tempuri.org/IService/RenameFolderResponse")]
        System.Threading.Tasks.Task<bool> RenameFolderAsync(System.Guid folderId, string newName, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RenameImage", ReplyAction="http://tempuri.org/IService/RenameImageResponse")]
        bool RenameImage(System.Guid imageId, string newName, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RenameImage", ReplyAction="http://tempuri.org/IService/RenameImageResponse")]
        System.Threading.Tasks.Task<bool> RenameImageAsync(System.Guid imageId, string newName, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteFolder", ReplyAction="http://tempuri.org/IService/DeleteFolderResponse")]
        void DeleteFolder(System.Guid folderId, System.Nullable<System.Guid> newFolderId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteFolder", ReplyAction="http://tempuri.org/IService/DeleteFolderResponse")]
        System.Threading.Tasks.Task DeleteFolderAsync(System.Guid folderId, System.Nullable<System.Guid> newFolderId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteImage", ReplyAction="http://tempuri.org/IService/DeleteImageResponse")]
        void DeleteImage(System.Guid imageId, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteImage", ReplyAction="http://tempuri.org/IService/DeleteImageResponse")]
        System.Threading.Tasks.Task DeleteImageAsync(System.Guid imageId, System.Guid contextId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : YAShop.ImagesClient.Images.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<YAShop.ImagesClient.Images.IService>, YAShop.ImagesClient.Images.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public YAShop.ImagesClient.Images.Folder[] GetFoldersTree(System.Guid contextId) {
            return base.Channel.GetFoldersTree(contextId);
        }
        
        public System.Threading.Tasks.Task<YAShop.ImagesClient.Images.Folder[]> GetFoldersTreeAsync(System.Guid contextId) {
            return base.Channel.GetFoldersTreeAsync(contextId);
        }
        
        public YAShop.ImagesClient.Images.Image[] GetImages(System.Nullable<System.Guid> folderId, System.Guid contextId) {
            return base.Channel.GetImages(folderId, contextId);
        }
        
        public System.Threading.Tasks.Task<YAShop.ImagesClient.Images.Image[]> GetImagesAsync(System.Nullable<System.Guid> folderId, System.Guid contextId) {
            return base.Channel.GetImagesAsync(folderId, contextId);
        }
        
        public System.Guid AddFolder(string name, System.Nullable<System.Guid> parentId, System.Guid contextId) {
            return base.Channel.AddFolder(name, parentId, contextId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> AddFolderAsync(string name, System.Nullable<System.Guid> parentId, System.Guid contextId) {
            return base.Channel.AddFolderAsync(name, parentId, contextId);
        }
        
        public System.Guid UploadImage(string name, byte[] data, System.Nullable<System.Guid> folderId, System.Guid contextId) {
            return base.Channel.UploadImage(name, data, folderId, contextId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> UploadImageAsync(string name, byte[] data, System.Nullable<System.Guid> folderId, System.Guid contextId) {
            return base.Channel.UploadImageAsync(name, data, folderId, contextId);
        }
        
        public bool RenameFolder(System.Guid folderId, string newName, System.Guid contextId) {
            return base.Channel.RenameFolder(folderId, newName, contextId);
        }
        
        public System.Threading.Tasks.Task<bool> RenameFolderAsync(System.Guid folderId, string newName, System.Guid contextId) {
            return base.Channel.RenameFolderAsync(folderId, newName, contextId);
        }
        
        public bool RenameImage(System.Guid imageId, string newName, System.Guid contextId) {
            return base.Channel.RenameImage(imageId, newName, contextId);
        }
        
        public System.Threading.Tasks.Task<bool> RenameImageAsync(System.Guid imageId, string newName, System.Guid contextId) {
            return base.Channel.RenameImageAsync(imageId, newName, contextId);
        }
        
        public void DeleteFolder(System.Guid folderId, System.Nullable<System.Guid> newFolderId, System.Guid contextId) {
            base.Channel.DeleteFolder(folderId, newFolderId, contextId);
        }
        
        public System.Threading.Tasks.Task DeleteFolderAsync(System.Guid folderId, System.Nullable<System.Guid> newFolderId, System.Guid contextId) {
            return base.Channel.DeleteFolderAsync(folderId, newFolderId, contextId);
        }
        
        public void DeleteImage(System.Guid imageId, System.Guid contextId) {
            base.Channel.DeleteImage(imageId, contextId);
        }
        
        public System.Threading.Tasks.Task DeleteImageAsync(System.Guid imageId, System.Guid contextId) {
            return base.Channel.DeleteImageAsync(imageId, contextId);
        }
    }
}
