//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprut.ImageStoreClient.ImageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folder", Namespace="http://schemas.datacontract.org/2004/07/ImagesStoreHost")]
    [System.SerializableAttribute()]
    public partial class Folder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Image", Namespace="http://schemas.datacontract.org/2004/07/ImageStoreHost.Domain")]
    [System.SerializableAttribute()]
    public partial class Image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((this.FolderField.Equals(value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        void AddFolder(string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFolder", ReplyAction="http://tempuri.org/IService/AddFolderResponse")]
        System.Threading.Tasks.Task AddFolderAsync(string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFolder", ReplyAction="http://tempuri.org/IService/GetFolderResponse")]
        Sprut.ImageStoreClient.ImageService.Folder GetFolder(string name, System.Nullable<System.Guid> parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFolder", ReplyAction="http://tempuri.org/IService/GetFolderResponse")]
        System.Threading.Tasks.Task<Sprut.ImageStoreClient.ImageService.Folder> GetFolderAsync(string name, System.Nullable<System.Guid> parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagesInFolder", ReplyAction="http://tempuri.org/IService/GetImagesInFolderResponse")]
        Sprut.ImageStoreClient.ImageService.Image[] GetImagesInFolder(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImagesInFolder", ReplyAction="http://tempuri.org/IService/GetImagesInFolderResponse")]
        System.Threading.Tasks.Task<Sprut.ImageStoreClient.ImageService.Image[]> GetImagesInFolderAsync(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSubFolders", ReplyAction="http://tempuri.org/IService/GetSubFoldersResponse")]
        Sprut.ImageStoreClient.ImageService.Folder[] GetSubFolders(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSubFolders", ReplyAction="http://tempuri.org/IService/GetSubFoldersResponse")]
        System.Threading.Tasks.Task<Sprut.ImageStoreClient.ImageService.Folder[]> GetSubFoldersAsync(System.Nullable<System.Guid> folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadImage", ReplyAction="http://tempuri.org/IService/UploadImageResponse")]
        System.Guid UploadImage(byte[] data, string fileNameOrigin, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadImage", ReplyAction="http://tempuri.org/IService/UploadImageResponse")]
        System.Threading.Tasks.Task<System.Guid> UploadImageAsync(byte[] data, string fileNameOrigin, string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImageUrl", ReplyAction="http://tempuri.org/IService/GetImageUrlResponse")]
        string GetImageUrl(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetImageUrl", ReplyAction="http://tempuri.org/IService/GetImageUrlResponse")]
        System.Threading.Tasks.Task<string> GetImageUrlAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTmbUrl", ReplyAction="http://tempuri.org/IService/GetTmbUrlResponse")]
        string GetTmbUrl(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTmbUrl", ReplyAction="http://tempuri.org/IService/GetTmbUrlResponse")]
        System.Threading.Tasks.Task<string> GetTmbUrlAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Sprut.ImageStoreClient.ImageService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Sprut.ImageStoreClient.ImageService.IService>, Sprut.ImageStoreClient.ImageService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddFolder(string name, string path) {
            base.Channel.AddFolder(name, path);
        }
        
        public System.Threading.Tasks.Task AddFolderAsync(string name, string path) {
            return base.Channel.AddFolderAsync(name, path);
        }
        
        public Sprut.ImageStoreClient.ImageService.Folder GetFolder(string name, System.Nullable<System.Guid> parentId) {
            return base.Channel.GetFolder(name, parentId);
        }
        
        public System.Threading.Tasks.Task<Sprut.ImageStoreClient.ImageService.Folder> GetFolderAsync(string name, System.Nullable<System.Guid> parentId) {
            return base.Channel.GetFolderAsync(name, parentId);
        }
        
        public Sprut.ImageStoreClient.ImageService.Image[] GetImagesInFolder(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetImagesInFolder(folderId);
        }
        
        public System.Threading.Tasks.Task<Sprut.ImageStoreClient.ImageService.Image[]> GetImagesInFolderAsync(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetImagesInFolderAsync(folderId);
        }
        
        public Sprut.ImageStoreClient.ImageService.Folder[] GetSubFolders(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetSubFolders(folderId);
        }
        
        public System.Threading.Tasks.Task<Sprut.ImageStoreClient.ImageService.Folder[]> GetSubFoldersAsync(System.Nullable<System.Guid> folderId) {
            return base.Channel.GetSubFoldersAsync(folderId);
        }
        
        public System.Guid UploadImage(byte[] data, string fileNameOrigin, string folder) {
            return base.Channel.UploadImage(data, fileNameOrigin, folder);
        }
        
        public System.Threading.Tasks.Task<System.Guid> UploadImageAsync(byte[] data, string fileNameOrigin, string folder) {
            return base.Channel.UploadImageAsync(data, fileNameOrigin, folder);
        }
        
        public string GetImageUrl(System.Guid id) {
            return base.Channel.GetImageUrl(id);
        }
        
        public System.Threading.Tasks.Task<string> GetImageUrlAsync(System.Guid id) {
            return base.Channel.GetImageUrlAsync(id);
        }
        
        public string GetTmbUrl(System.Guid id) {
            return base.Channel.GetTmbUrl(id);
        }
        
        public System.Threading.Tasks.Task<string> GetTmbUrlAsync(System.Guid id) {
            return base.Channel.GetTmbUrlAsync(id);
        }
    }
}
